# uncomment the following line and set it to your Webxdc name - otherwise the file name will be used
#name = "Hello World!"

# uncomment the following line and set it your source repo; it is shown in the Webxdc's menu then
#source_code_url = "https://gitsth.org/your/repo"
